import Foundation

// Generated by arrdeck/frontend/scripts/palettes.py, with the PWA's blocks in
// index.css: the palettes' published colours, nudged only where one missed
// the contrast arrdeck holds to. Regenerate both together.

/// One mode of a palette, as 0xRRGGBB values.
public struct PaletteTokens: Sendable, Equatable {
    public let background, card, raised, line, text, muted, accent, success, warning, danger: UInt32
}

/// The editor palettes beside arrdeck's own, which uses the system colours.
public enum Palette: String, CaseIterable, Sendable, Hashable {
    case arrdeck
    case catppuccin
    case dracula
    case nord
    case gruvbox
    case solarized
    case tokyonight
    case onedark
    case rosepine

    public var name: String {
        switch self {
        case .arrdeck: "arrdeck"
        case .catppuccin: "Catppuccin"
        case .dracula: "Dracula"
        case .nord: "Nord"
        case .gruvbox: "Gruvbox"
        case .solarized: "Solarized"
        case .tokyonight: "Tokyo Night"
        case .onedark: "One Dark"
        case .rosepine: "Rosé Pine"
        }
    }

    /// The official light and dark names, where they differ from the palette's.
    public var variants: String? {
        switch self {
        case .catppuccin: "Latte · Mocha"
        case .dracula: nil
        case .nord: "Snow Storm · Polar Night"
        case .gruvbox: nil
        case .solarized: nil
        case .tokyonight: "Day · Night"
        case .onedark: "One Light · One Dark"
        case .rosepine: "Dawn · Main"
        case .arrdeck: nil
        }
    }

    public var dark: PaletteTokens? {
        switch self {
        case .arrdeck: nil
        case .catppuccin: PaletteTokens(background: 0x181825, card: 0x1e1e2e, raised: 0x313244, line: 0x45475a, text: 0xcdd6f4, muted: 0xa6adc8, accent: 0xcba6f7, success: 0xa6e3a1, warning: 0xf9e2af, danger: 0xf38ba8)
        case .dracula: PaletteTokens(background: 0x21222c, card: 0x282a36, raised: 0x44475a, line: 0x44475a, text: 0xf8f8f2, muted: 0x8491b6, accent: 0xbd93f9, success: 0x50fa7b, warning: 0xf1fa8c, danger: 0xff5c5c)
        case .nord: PaletteTokens(background: 0x2e3440, card: 0x3b4252, raised: 0x434c5e, line: 0x4c566a, text: 0xeceff4, muted: 0xd8dee9, accent: 0x88c0d0, success: 0xa3be8c, warning: 0xebcb8b, danger: 0xce858c)
        case .gruvbox: PaletteTokens(background: 0x1d2021, card: 0x282828, raised: 0x3c3836, line: 0x504945, text: 0xebdbb2, muted: 0xa89984, accent: 0x83a598, success: 0xb8bb26, warning: 0xfabd2f, danger: 0xfb4934)
        case .solarized: PaletteTokens(background: 0x002b36, card: 0x073642, raised: 0x0e4553, line: 0x1f5664, text: 0xa0acac, muted: 0x8c9b9d, accent: 0x2f90d4, success: 0x859900, warning: 0xb58900, danger: 0xe45f5d)
        case .tokyonight: PaletteTokens(background: 0x16161e, card: 0x1a1b26, raised: 0x292e42, line: 0x3b4261, text: 0xc0caf5, muted: 0x7a81a9, accent: 0x7aa2f7, success: 0x9ece6a, warning: 0xe0af68, danger: 0xf7768e)
        case .onedark: PaletteTokens(background: 0x21252b, card: 0x282c34, raised: 0x3b4048, line: 0x3e4451, text: 0xabb2bf, muted: 0x8d939e, accent: 0x61afef, success: 0x98c379, warning: 0xe5c07b, danger: 0xe06c75)
        case .rosepine: PaletteTokens(background: 0x191724, card: 0x1f1d2e, raised: 0x26233a, line: 0x403d52, text: 0xe0def4, muted: 0x908caa, accent: 0xc4a7e7, success: 0x9ccfd8, warning: 0xf6c177, danger: 0xeb6f92)
        }
    }

    /// nil where the palette has no light variant: choosing it pins dark.
    public var light: PaletteTokens? {
        switch self {
        case .arrdeck: nil
        case .catppuccin: PaletteTokens(background: 0xe6e9ef, card: 0xeff1f5, raised: 0xdce0e8, line: 0xccd0da, text: 0x4c4f69, muted: 0x64677e, accent: 0x7e35de, success: 0x2d701e, warning: 0x8a5812, danger: 0xc50e36)
        case .dracula: nil
        case .nord: PaletteTokens(background: 0xe5e9f0, card: 0xeceff4, raised: 0xd8dee9, line: 0xd8dee9, text: 0x2e3440, muted: 0x4c566a, accent: 0x486384, success: 0x56654a, warning: 0x855648, danger: 0x954c53)
        case .gruvbox: PaletteTokens(background: 0xf2e5bc, card: 0xfbf1c7, raised: 0xebdbb2, line: 0xd5c4a1, text: 0x3c3836, muted: 0x70655c, accent: 0x076678, success: 0x67630c, warning: 0x86570f, danger: 0x9d0006)
        case .solarized: PaletteTokens(background: 0xeee8d5, card: 0xfdf6e3, raised: 0xe6dfca, line: 0xd9d2bd, text: 0x073642, muted: 0x566c73, accent: 0x1c679b, success: 0x5a6800, warning: 0x7b5d00, danger: 0xbb2a28)
        case .tokyonight: PaletteTokens(background: 0xd0d5e3, card: 0xe1e2e7, raised: 0xc4c8da, line: 0xb6bfe2, text: 0x2e51a0, muted: 0x3b59a4, accent: 0x1e529a, success: 0x455b2c, warning: 0x68502e, danger: 0xa21c43)
        case .onedark: PaletteTokens(background: 0xeaeaeb, card: 0xfafafa, raised: 0xe5e5e6, line: 0xd4d4d5, text: 0x383a42, muted: 0x666974, accent: 0x3461c4, success: 0x397238, warning: 0x895e01, danger: 0xb04238)
        case .rosepine: PaletteTokens(background: 0xf2e9e1, card: 0xfffaf3, raised: 0xf4ede8, line: 0xdfdad9, text: 0x575279, muted: 0x6b6688, accent: 0x76648b, success: 0x286983, warning: 0x916120, danger: 0x9d566a)
        }
    }

    public var darkOnly: Bool { self != .arrdeck && light == nil }
}
